Initial cut of planner GUI using Freya
MakerPnP/makerpnp pull request #5
Opened 2024-08-29 12:46 UTC by hydra

* Also includes commits from #4

2024-08-30 14:53 UTC, marc2332 requested changes
an idea

2024-08-30 14:53 UTC, marc2332 commented on crates/planner_gui/src/main.rs
> +}
```suggestion
fn use_change_language() -> Signal<Box<dyn i18>> {

    let mut i18n = use_i18();

	use_hook(move || Signal::new(Box::new(
		move |language_pair: &LanguagePair| {
			let mut guard = SELECTED_LANGUAGE.lock().unwrap();
		    (*guard).replace(language_pair.clone());
		
		    i18n.set_language(language_pair.code.parse().unwrap());
		}
	)))
}
```

2024-08-30 14:56 UTC, marc2332 commented on crates/planner_gui/src/main.rs
> +}
```rs
fn app() -> Element  {
	let change_lang = use_change_language();

	rsx!(
		Button { 
			onclick: move |_| change_lang.read()(...)
		}
	)
}
```

2025-03-25 12:24 UTC, hydra commented
In the end I didn't get on with using Freya and went with Cushy, but that too also turned out to be problematic (too small community, single developer).  most of the functionality of the cushy app has been ported to an egui app.

Thanks for the assistance while I tried Freya, much appreciated.

2025-03-25 12:24 UTC, closed without merging